Adapt manual-daily for the installation-guide on Alioth to Salsa move (some parts need fixing; and of course testing

diff --git a/scripts/manual-daily/build-devref b/scripts/manual-daily/build-devref
--- a/scripts/manual-daily/build-devref
+++ b/scripts/manual-daily/build-devref
@@ -9,7 +9,8 @@ else
     mainlog=/dev/stdout
 fi
 
-ALIOTH_DEVREF_PATH=/srv/alioth.debian.org/chroot/home/groups/d-i/htdocs/doc/internals
+### FIXME  fix ALIOTH_DEVREF_PATH
+#ALIOTH_DEVREF_PATH=/srv/alioth.debian.org/chroot/home/groups/d-i/htdocs/doc/internals
 
 usage() {
     if [ "$@" ]; then
@@ -32,27 +33,27 @@ checkfatal() {
 }
 
 is_updated() {
-    if egrep "^[UA].[[:space:]]" $logdir/svn_up_devref.log | \
+    if egrep "^[UA].[[:space:]]" $logdir/git_pull_devref.log | \
        grep -qv "^At revision"; then
         return 0
     fi
     return 1
 }
 
-update_from_svn() {
+update_from_git() {
     echo >>$mainlog
-    echo "Performing SVN update..." >>$mainlog
-    svn --non-interactive up >>$logdir/svn_up_devref.log 2>&1
+    echo "Performing GIT update..." >>$mainlog
+    git pull >>$logdir/git_pull_devref.log 2>&1
     RESULT=$?
     if [ ! $RESULT = 0 ]; then
-        echo "SVN update failed with code $RESULT" >>$mainlog
+        echo "GIT pull failed with code $RESULT" >>$mainlog
         echo >>$mainlog
-        cat $logdir/svn_up_devref.log >>$mainlog
+        cat $logdir/git_pull_devref.log >>$mainlog
         rm -f $ROOT/lockfile
         exit 1
     fi
-    if svn st 2>/dev/null | grep -q "^C"; then
-        checkfatal "C" "checking for conflicts after 'svn up'"
+    if [ -n "$(git status -s -uno .)" ] ; then
+        checkfatal "checking for conflicts after 'git pull'"
     fi
 }
 
@@ -89,11 +90,11 @@ if [ "$DI_BUILDING_FROM_MAIN" ] && [ "$DI_BUILD_DEVREF" != 1 ]; then
     rm -f $ROOT/lockfile
     exit 0
 else
-    : >$logdir/svn_up_devref.log
+    : >$logdir/git_pull_devref.log
     echo "Starting D-I Internals build -- $(date -u)" >>$mainlog
 fi
 
-update_from_svn
+update_from_git
 
 NR_BUILDS=0
 
@@ -104,11 +105,12 @@ if is_updated; then
 
     if [ "$DI_LOCAL_BUILD" = 1 ]; then
         echo "Local build! No changes have been uploaded." >>$mainlog
-    else
-        ## Copy the created files to alioth.debian.org
-        echo "rsyncing files to alioth..." >>$mainlog
-        rsync -qzr --perms *.html *.css alioth.debian.org:$ALIOTH_DEVREF_PATH/ >>$mainlog 2>&1
-        checkfatal "$?" "rsyncing D-I Internals"
+### FIXME
+###    else
+###        ## Copy the created files to alioth.debian.org
+###        echo "rsyncing files to alioth..." >>$mainlog
+###        rsync -qzr --perms *.html *.css alioth.debian.org:$ALIOTH_DEVREF_PATH/ >>$mainlog 2>&1
+###        checkfatal "$?" "rsyncing D-I Internals"
     fi
 else
     echo "No changes." >>$mainlog
diff --git a/scripts/manual-daily/build-manual b/scripts/manual-daily/build-manual
--- a/scripts/manual-daily/build-manual
+++ b/scripts/manual-daily/build-manual
@@ -5,7 +5,8 @@
 
 mainlog=$logdir/main.log
 
-ALIOTH_MAN_PATH=/srv/alioth.debian.org/chroot/home/groups/d-i/htdocs/manual
+### FIXME  fix ALIOTH_MAN_PATH
+#ALIOTH_MAN_PATH=/srv/alioth.debian.org/chroot/home/groups/d-i/htdocs/manual
 
 # Remove xml-containing directories for po-based languages, since they will
 # confuse translation statistics for xml-based languages.
@@ -56,7 +57,7 @@ is_updated() {
         grepexp="^[UA].[[:space:]]*${lang}/"
     fi
 
-    if egrep -q $grepexp $logdir/svn_up.log; then
+    if egrep -q $grepexp $logdir/git_pull.log; then
         return 0
     fi
     return 1
@@ -104,41 +105,39 @@ get_formats() {
     echo "$(echo "$formats" | sed "s:^ ::")"
 }
 
-update_from_svn() {
+update_from_git() {
     echo >>$mainlog
-    echo "Performing SVN update..." >>$mainlog
-    svn --non-interactive up >>$logdir/svn_up.log 2>&1
+    echo "Performing GIT update..." >>$mainlog
+    git pull >>$logdir/git_pull.log 2>&1
     RESULT=$?
     if [ ! $RESULT = 0 ]; then
-        echo "SVN update failed with code $RESULT" >>$mainlog
+        echo "GIT pull failed with code $RESULT" >>$mainlog
         echo >>$mainlog
-        cat $logdir/svn_up.log >>$mainlog
+        cat $logdir/git_pull.log >>$mainlog
         rm -f $ROOT/lockfile
         exit 1
     fi
-    if svn st 2>/dev/null | grep -q "^C"; then
-        checkfatal "C" "checking for conflicts after 'svn up'"
+    if [ -n "$(git status -s -uno .)" ] ; then
+        checkfatal "checking for conflicts after 'git pull'"
     fi
 }
 
-commit_to_svn() {
-    echo "Committing changes in manual/po to SVN..." >>$mainlog
-    SVN_NEW_LIST=$(svn st po/pot/ 2>/dev/null | grep "^\?[[:space:]].*\.pot" | sed "s/^\?[[:space:]]*//")
-    if [ "$SVN_NEW_LIST" ]; then
-        echo "Adding new POT files:" >>$logdir/svn_ci.log
-        for SVN_NEW in $SVN_NEW_LIST; do
-            svn add $SVN_NEW >>$logdir/svn_ci.log 2>&1
-            checkfatal "$?" "running 'svn add' on $SVN_NEW"
-        done
-    fi
-    if svn st po/ 2>/dev/null | grep -q "^[AM]"; then
-#       echo "Actual commit disabled, showing svn st:" >>$logdir/svn_ci.log
-#       svn st po/ 2>/dev/null >>$logdir/svn_ci.log 2>&1
-        echo "Committing changed files:" >>$logdir/svn_ci.log
-        svn ci po/ -m "[SILENT_COMMIT] Update of POT and PO files for the manual" >>$logdir/svn_ci.log 2>&1
-        checkfatal "$?" "committing POT/PO files to SVN"
-        if svn st po/ 2>/dev/null | grep -q "^C"; then
-            checkfatal "C" "checking for conflicts in manual/po after 'svn ci'"
+commit_to_git() {
+    echo "Committing/pushing changes in manual/po to GIT..." >>$mainlog
+        echo "Adding new POT files..." >>$logdir/git_push.log
+            git add */*.pot
+
+###           checkfatal "$?" "running 'svn add' on $SVN_NEW"
+#       echo "Actual commit disabled, showing svn st:" >>$logdir/git_push.log
+#       svn st po/ 2>/dev/null >>$logdir/git_push.log 2>&1
+
+        echo "Committing changed po files:" >>$logdir/git_push.log
+           git add */*.po
+           git commit -m "[SILENT_COMMIT] Update of POT and PO files for the installation-guide" >>$logdir/git_push.log 2>&1
+
+###        checkfatal "$?" "committing POT/PO files to SVN"
+
+###        checkfatal "checking for conflicts in manual/po after 'git push'"
         fi
     else
         echo "  No updates to commit" >>$mainlog
@@ -171,7 +170,7 @@ build_lang() {
                 continue
                 ;;
         esac
-        if ! egrep -q $grepexp $logdir/svn_up.log; then
+        if ! egrep -q $grepexp $logdir/git_pull.log; then
             echo "NOTE: extra build!" >>$mainlog
         fi
 
@@ -187,7 +186,7 @@ build_lang() {
         for arch in $buildarchs; do
             destsuffix="${lang}.${arch}"
             if [ $BUILDRESULT = 0 ]; then
-                echo "Building manual for $arch" >>$langlog
+                echo "Building installation-guide for $arch" >>$langlog
                 echo -n "  $arch" >>$mainlog
 
                 ./buildone.sh "$arch" "$lang" "$formats" &>$langlog.arch
@@ -212,7 +211,7 @@ build_lang() {
                         ;;
                     *)
                         BUILDRESULT=1
-                        echo "Errors while building manual for $arch" >>$langlog
+                        echo "Errors while building installation-guide for $arch" >>$langlog
                         ;;
                 esac
                 if [ $BUILDRESULT = 0 ]; then
@@ -229,29 +228,29 @@ build_lang() {
                     echo "Note: remaining architectures will not be built" >>$langlog
                     echo >>$langlog
                     echo >>$mainlog
-                    echo "  Error: fatal error building manual for $lang.$arch" >>$mainlog
+                    echo "  Error: fatal error building installation-guide for $lang.$arch" >>$mainlog
                 fi
                 ./clear.sh
 
                 # Sleep a bit to allow the system to cool down...
                 #sleep 30s
             else
-                echo "*** Not building manual for $lang.$arch" >>$langlog
+                echo "*** Not building installation-guide for $lang.$arch" >>$langlog
             fi
         done
 
         rm $langlog.arch
         [ $BUILDRESULT = 0 ] && echo >>$mainlog
 
-        if [ "$DI_LOCAL_BUILD" != 1 ]; then
-            # Upload logfile to alioth
-            scp $logdir/$lang.log alioth.debian.org:$ALIOTH_MAN_PATH/logs/
-            if [ $? = 0 ]; then
-                echo "  Upload of $lang.log success" >>$mainlog
-            else
-                echo "  Upload of $lang.log failed" >>$mainlog
-            fi
-	fi
+###        if [ "$DI_LOCAL_BUILD" != 1 ]; then
+###            # Upload logfile to alioth
+### FIXME            scp $logdir/$lang.log alioth.debian.org:$ALIOTH_MAN_PATH/logs/
+###            if [ $? = 0 ]; then
+###                echo "  Upload of $lang.log success" >>$mainlog
+###            else
+###                echo "  Upload of $lang.log failed" >>$mainlog
+###            fi
+###	fi
 
         # Check if any architectures have actually been built
         if ls $destination | grep -q "$lang\."; then
@@ -266,7 +265,7 @@ build_lang() {
     return $BUILDRESULT
 }
 
-# We want the manual files group writable
+# We want the installation-guide files group writable
 umask 0002
 
 RETRY=""
@@ -318,36 +317,37 @@ architectures=$(egrep -v "^[[:space:]]*(|#.*)$" $ROOT/bin/archlist | cut -f 1)
 rm -R $destination/* &>/dev/null
 
 export manual_release="stretch"
+### FIXME    fix 'for_alioth'
 export manual_target="for_alioth"
 
 if [ "$DI_BUILDING_FROM_MAIN" ] && [ "$DI_BUILD_MANUAL" = 0 ]; then
-    echo "Not building D-I Manual (as per configuration settings)" >$mainlog
+    echo "Not building D-I installation-guide (as per configuration settings)" >$mainlog
     rm -f $ROOT/lockfile
     exit 0
 elif [ -z "$RETRY" ]; then
-    : >$logdir/svn_up.log
-    : >$logdir/svn_ci.log
-    echo "Starting D-I Manual build -- $(date -u)" >$mainlog
+    : >$logdir/git_pull.log
+    : >$logdir/git_push.log
+    echo "Starting D-I installation-guide build -- $(date -u)" >$mainlog
 else
     echo >>$mainlog
     echo >>$mainlog
-    echo "Starting D-I Manual build (RETRY) -- $(date -u)" >>$mainlog
+    echo "Starting D-I installation-guide build (RETRY) -- $(date -u)" >>$mainlog
 fi
 
-update_from_svn
+update_from_git
 echo >>$mainlog
 
 NR_BUILDS=0
 
-# Build the manual for English
+# Build the installation-guide for English
 EN_UPDATED=""
 if is_updated en; then
     EN_UPDATED=1
     langlog=$logdir/en.log
     : >$langlog
-    echo "Info: manual for en has been changed" >>$mainlog
+    echo "Info: installation-guide for en has been changed" >>$mainlog
     echo "Preparing build for language $lang - $(date -u)" >>$langlog
-    echo "Info: building manual from XML files" >>$langlog
+    echo "Info: building installation-guide from XML files" >>$langlog
 
     build_lang en
     checkfatal "$?" "build for English"
@@ -361,12 +361,12 @@ if is_updated en || [ ! -d "$source/integrated/en" ]; then
     checkfatal "$?" "updating templates"
     echo >>$mainlog
 
-    # Extract preconfiguration example from the manual
+    # Extract preconfiguration example from the installation-guide
     cd $source/build
     PRESEED="../en/appendix/preseed.xml"
     if [ -f $PRESEED ] && [ -x preseed.pl ]; then
         ./preseed.pl -r $manual_release $PRESEED >$destination/example-preseed.txt
-        echo "Extracting example-preseed.txt from manual" >>$mainlog
+        echo "Extracting example-preseed.txt from installation-guide" >>$mainlog
         echo >>$mainlog
     fi
     cd ..
@@ -400,12 +400,12 @@ for lang in $translations; do
 
     if is_updated "$lang" || do_extra "$lang"; then
         if uses_po "$lang"; then
-            echo "Info: building manual from PO files" >>$langlog
+            echo "Info: building installation-guide from PO files" >>$langlog
             generate_xml $lang >>$langlog 2>&1
             checkfatal "$?" "generating xml for $lang"
             echo "Info: generation of XML files complete" >>$langlog
         else
-            echo "Info: building manual from XML files" >>$langlog
+            echo "Info: building installation-guide from XML files" >>$langlog
         fi
         echo >>$langlog
     fi
@@ -452,11 +452,11 @@ done
    fi
 
 echo >>$mainlog
-# Commit updates to POT and PO files to SVN
+# Commit updates to POT and PO files to GIT
 if [ "$DI_LOCAL_BUILD" = 1 ]; then
-    echo "Local build! Changes to POT/PO files are not committed to SVN." >>$mainlog
+    echo "Local build! Changes to POT/PO files are not committed/pushed to GIT." >>$mainlog
 else
-    commit_to_svn
+    commit_to_git
 fi
 
 echo >>$mainlog
@@ -480,12 +480,12 @@ if [ $NR_BUILDS -gt 0 ]; then
     if [ "$DI_LOCAL_BUILD" = 1 ]; then
         echo "Local build! No changes have been uploaded." >>$mainlog
     else
-        echo "rsyncing files to alioth..." >>$mainlog
-        rsync -qz --perms * alioth.debian.org\:$ALIOTH_MAN_PATH/ >>$mainlog 2>&1
+### FIXME        echo "rsyncing files to alioth..." >>$mainlog
+###        rsync -qz --perms * alioth.debian.org\:$ALIOTH_MAN_PATH/ >>$mainlog 2>&1
         # rsync subdirectories individually so we can also delete obsolete files
-        for i in $(find . -type d | grep -v "^\.$"); do
-            rsync -qzr --perms --delete "$i" alioth.debian.org\:$ALIOTH_MAN_PATH/ >>$mainlog 2>&1
-            checkfatal "$?" "rsync of '$i'"
+###        for i in $(find . -type d | grep -v "^\.$"); do
+###            rsync -qzr --perms --delete "$i" alioth.debian.org\:$ALIOTH_MAN_PATH/ >>$mainlog 2>&1
+###            checkfatal "$?" "rsync of '$i'"
         done
     fi
 else
@@ -495,9 +495,10 @@ fi
 # Clean up some
 find $source/po -name "*.po~" -exec rm {} +
 if [ "$DI_LOCAL_BUILD" = 1 ]; then
-	# Needed to avoid conflicts with next svn update
+	# Needed to avoid conflicts with next git pull
         echo "Reverting changes in PO files..." >>$mainlog
-	svn revert -R $source/po >>$mainlog 2>&1
+        cd $source/po
+	git checkout -- * >>$mainlog 2>&1
 fi
 
 echo >>$mainlog
