Overhaul of build-manual for the installation-guide (I don't want the builds to be disabled on errors; instead just try again, when there are changings)

diff --git a/scripts/manual-daily/build-manual b/scripts/manual-daily/build-manual
--- a/scripts/manual-daily/build-manual
+++ b/scripts/manual-daily/build-manual
@@ -12,10 +12,7 @@ DILLON_MANUAL_PATH=/srv/d-i.debian.org/www/doc/installation-guide
 # They will later be freshly generated anyway.
 # 
 # ! Include all po-based languages here !
-rm -fR $source/ca $source/cs $source/da $source/de $source/el $source/es $source/fi
-rm -fR $source/fr $source/hu $source/it $source/ja $source/kab $source/ko $source/nb
-rm -fR $source/nl $source/nn $source/pt $source/ro $source/ru $source/sv $source/tl
-rm -fR $source/uk $source/vi $source/zh_CN $source/zh_TW
+rm -fR $source/ca $source/cs $source/da $source/de $source/el $source/es $source/fi $source/fr $source/hu $source/it $source/ja $source/kab $source/ko $source/nb $source/nl $source/nn $source/pt $source/ro $source/ru $source/sv $source/tl $source/uk $source/vi $source/zh_CN $source/zh_TW
 
 usage() {
     if [ "$@" ]; then
@@ -28,15 +25,16 @@ usage() {
 }
 
 ## Function to check result of executed programs and exit on error
-checkfatal() {
-    if [ ! "$1" = "0" ]; then
-        echo "Unexpected error $1 while $2" >>$mainlog
-        touch $ROOT/do_not_build
-        echo "!!!! Autobuilding has been disabled !!!!" >>$mainlog
-        rm -f $ROOT/lockfile
-        exit 999
-    fi
-}
+##### DO NOT USE THIS ANYMORE. IN CASE OF ERRORS, SIMPLY WAIT FOR FIXES TO ARRIVE, AND THEN JUST TRY TO BUILD AGAIN.
+#####checkfatal() {
+#####    if [ ! "$1" = "0" ]; then
+#####        echo "Unexpected error $1 while $2" >>$mainlog
+#####        touch $ROOT/do_not_build
+#####        echo "!!!! Autobuilding has been disabled !!!!" >>$mainlog
+#####        rm -f $ROOT/lockfile
+#####        exit 999
+#####    fi
+#####}
 
 uses_po() {
     local lang=$1
@@ -114,7 +112,7 @@ get_formats() {
 update_from_git() {
     echo >>$mainlog
     echo "Performing GIT update..." >>$mainlog
-    git pull >>$logdir/git_pull.log 2>&1
+    git pull origin master >>$logdir/git_pull.log 2>&1
     RESULT=$?
     if [ ! $RESULT = 0 ]; then
         echo "GIT pull failed with code $RESULT" >>$mainlog
@@ -124,7 +122,8 @@ update_from_git() {
         exit 1
     fi
     if [ -n "$(git status -s -uno .)" ] ; then
-        checkfatal "checking for conflicts after 'git pull'"
+#####        checkfatal "checking for conflicts after 'git pull'"
+        echo
     fi
 }
 
@@ -335,7 +334,7 @@ if is_updated en || global_build_options_changed; then
     echo "Info: building installation-guide from XML files" >>$langlog
 
     build_lang en
-    checkfatal "$?" "build for English"
+#####    checkfatal "$?" "build for English"
     echo >>$mainlog
 fi
 
@@ -343,7 +342,7 @@ fi
 cd $source
 if is_updated en || [ ! -d "$source/integrated/en" ] || global_build_options_changed; then
     update_templates >>$mainlog 2>&1
-    checkfatal "$?" "updating templates"
+#####    checkfatal "$?" "updating templates"
     echo >>$mainlog
 
     # Extract preconfiguration example from the installation-guide
@@ -374,7 +373,7 @@ for lang in $translations; do
         if is_updated "$lang" || [ "$EN_UPDATED" ]; then
             echo "Info: updating PO files for $lang" >>$mainlog
             update_po $lang >>$langlog 2>&1
-            checkfatal "$?" "updating po for $lang"
+#####            checkfatal "$?" "updating po for $lang"
         fi
     fi
 
@@ -382,7 +381,7 @@ for lang in $translations; do
         if uses_po "$lang"; then
             echo "Info: building installation-guide from PO files" >>$langlog
             generate_xml $lang >>$langlog 2>&1
-            checkfatal "$?" "generating xml for $lang"
+#####            checkfatal "$?" "generating xml for $lang"
             echo "Info: generation of XML files complete" >>$langlog
         else
             echo "Info: building installation-guide from XML files" >>$langlog
