scripts/git-setup: Allow setting the access mode explicitly
This auto-detection is kind of weird as it requires the top level
repository to be manually reconfigured if one ever changes from
anonymous to authenticated access.  Allow specifying this
explicitly.

diff --git a/scripts/git-setup b/scripts/git-setup
--- a/scripts/git-setup
+++ b/scripts/git-setup
@@ -22,26 +22,47 @@ config_git_auth () {
 	runshow git config --global "url.$AUTH_BASE_URL.pushInsteadOf" "$ANON_BASE_URL"
 }
 
-if [ -d .svn ]; then
-    URL=$(LANG=C svn info| grep '^URL' | awk '{print $2}')
-elif [ -d .git ]; then
-    URL=$({ git config --local --get-regexp '^remote\..*\.pushUrl$' || true; git config --local --get-regexp '^remote\..*\.url$'; } | awk '/'"$COMMON_URL_REGEXP"'/ { print $2; exit }')
-else
-    echo "Can't work out what VCS you're using. Abort." >&2
-    exit 1
-fi
-case "$URL" in
+config_auto () {
+    if [ -d .svn ]; then
+	URL=$(LANG=C svn info| grep '^URL' | awk '{print $2}')
+    elif [ -d .git ]; then
+	URL=$({ git config --local --get-regexp '^remote\..*\.pushUrl$' || true; git config --local --get-regexp '^remote\..*\.url$'; } | awk '/'"$COMMON_URL_REGEXP"'/ { print $2; exit }')
+    else
+	echo "Can't work out what VCS you're using. Abort." >&2
+	exit 1
+    fi
+    case "$URL" in
 	*ssh*|git@salsa*)
-		echo "Your working copy is using $URL, so setting up git with auth"
-		config_git_auth
-	;;
+	    echo "Your working copy is using $URL, so setting up git with auth"
+	    config_git_auth
+	    ;;
 	svn*|http*)
-		echo "Your working copy is using $URL, so setting up git anon"
-		config_git_anon
-	;;
+	    echo "Your working copy is using $URL, so setting up git anon"
+	    config_git_anon
+	    ;;
 	*)
-		echo "unknown VCS url: $URL" >&2
-		exit 1
+	    echo "unknown VCS url: $URL" >&2
+	    exit 1
+	    ;;
+    esac
+}
+
+case "${1:-}" in
+    anon*)
+	config_git_anon
+	;;
+
+    auth*)
+	config_git_auth
+	;;
+
+    '')
+	config_auto
+	;;
+
+    *)
+	echo >&2 "Usage: $0 [anon | auth]"
+	exit 2
 	;;
 esac
 
